### PR TITLE
Fixed image in README.rst

### PR DESCRIPTION
**Pull request by dherrada**

### CODE REVIEW

**Comment by dherrada** [comment]
Anyone have any clue why Travis is not passing? I've verified that the image is readable.

**Comment by sommersoft** [comment]
@dherrada looks like adding `../` before `docs` succeeds:
```shell
~/Dev/circuitpython_libs/Adafruit_CircuitPython_CircuitPlayground/docs:$> git diff
diff --git a/README.rst b/README.rst
index 3b69922..73c3f7e 100644
--- a/README.rst
+++ b/README.rst
@@ -16,7 +16,7 @@ Introduction
 
 This high level library provides objects that represent CircuitPlayground hardware.
 
-.. image :: /_static/circuitplayground_express.jpg
+.. image :: ../docs/_static/circuitplayground_express.jpg
     :target: https://adafruit.com/product/3333
     :alt: CircuitPlayground Express

~/Dev/circuitpython_libs/Adafruit_CircuitPython_CircuitPlayground/docs:$> sphinx-build -E -W -b html . _build/html
Running Sphinx v2.0.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/3.4/objects.inv...
loading intersphinx inventory from https://circuitpython.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://circuitpython.readthedocs.io/projects/neopixel/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [100%] index                                                                         
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                          
generating indices... genindex py-modindex
highlighting module code... [100%] adafruit_circuitplayground.express                                   
writing additional pages... search/home/sommersoft/.local/lib/python3.6/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}

copying images... [100%] ../docs/_static/circuitplayground_express.jpg                                  
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
```

**Comment by dherrada** [comment]
Thanks for the help!

**Comment by dherrada** [comment]
@sommersoft So it looks like the only way to get travis to pass is to use ../docs, and the only way to have the image show up is with docs or ./docs

**Pull request merged**
