### PR TITLE
added exception on importing lib on a non-cp board

### PR DESCRIPTION
**Pull request by ChrisPappalardo**
Added an import exception if the platform is not recognized when importing the lib

### CODE REVIEW

**Comment by tekktrik** [comment]
@caternuson, @Neradoc - we discussed this in the related issue (#121).  What are y'all's thoughts?

**Comment by caternuson** [comment]
LGTM. Not sure what is messing with the doc build in the first CI run.

I'd suggest this approach vs. #125. If this is going to require defining a new class as in #125, then not worth the effort. This is a rare edge case and a minor point of confusion when hit.

**Comment by kattni** [comment]
Reopening. I see that @caternuson prefers this over #125.

@caternuson The CI issue is failing because Sphinx is trying to run it from its own platform, and because Linux isn't supported, it fails. I tried adding the library itself to `autodoc_mock_imports`, and it fails as a warning on "Mock object detected." I found that you can `suppress_warnings` and this warning has a subtype of `"mocked_object"` or something close to that, but I tried a bunch of formats for adding that to `conf.py`, and none of them worked. There's probably something there, but I'm not seeing it.

**Comment by caternuson** [comment]
Yep, thanks @ChrisPappalardo for giving it a go. Bummer that the CI/sphinx through a bit of a wrench in this in terms of a solution.

**Comment by ChrisPappalardo** [comment]
@caternuson no worries, happy to help, glad we were able to close out the issue!

**Pull request closed without merging**
