### PR TITLE
Create “Gravity Pulls Pixel” program

### PR DESCRIPTION
**Pull request by dcbriccetti**
This program uses the Circuit Playground Express’s accelerometer to position
a white pixel as if gravity were pulling it.

This may be too complicated to belong here. Please let me know if it is, and if there’s somewhere else within Adafruit where it could be useful. Otherwise I’ll just publish it within my own sphere.

Video here: https://youtu.be/sZ4tNOUKRpw

### CODE REVIEW

**Comment by dcbriccetti** [comment]
Hi Kattni. How about we call the subfolder `advanced`, since `examples` is lower case, and it’s inside a folder `examples` we already know it’s examples?

**Comment by dcbriccetti** [comment]
The style check doesn’t like 
```
    smaller = min(a1, a2)
    larger  = max(a1, a2)
```
But don’t we prefer that to:
```
    smaller = min(a1, a2)
    larger = max(a1, a2)
```

**Comment by kattni** [comment]
I would prefer it be called `advanced examples`. I understand it is already in the examples folder, but I feel being more explicit is better. Lowercase is fine.

Having things lined up is a personal preference, however if you choose to do so, you must disable the pylint checks. I personally don't bother with lining things up, I go with proper spacing, but that is my preference.

**Comment by dcbriccetti** [comment]
I rebased to combine commits, and force pushed. If this passes, it’s ready as far as I’m concerned. Thanks!

**Comment by dcbriccetti** [comment]
I don’t understand the Travis error. Also, is the space in `advanced examples` OK?

**Comment by kattni** [comment]
Space should be ok, but we can underscore it instead for consistency. I don't think that's the issue. I think the issue is in how Travis looks to run pylint on the files. I believe we'll need to update `.travis.yml`. Give me a bit here to sort this out.

**Comment by kattni** [comment]
@dcbriccetti Ok I need to get some help on this one. I know what needs to happen but not entirely how to do it, and I believe that we need to update some further tools to deal with a subfolder. This is something I believe we would have eventually needed to do anyway, it happens to be that you're the first test case for it! I appreciate your patience. I'll keep you posted.

**Comment by dcbriccetti** [comment]
Sure! No rush. Glad to help you stretch things.

**Comment by kattni** [comment]
@dcbriccetti Still looking into this, haven't been able to coordinate with the person I need to yet. Wanted to give you an update.

**Comment by dcbriccetti** [comment]
Thanks. That’s thoughtful.

**Comment by kattni** [comment]
@dcbriccetti Please make the following change to `.travis.yml`:
Replace line 30
```
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
```
with
```
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name `find ./examples -name "*.py"`)
```
And let's see if that appeases Travis!

**Comment by kattni** [comment]
@dcbriccetti Thank you for making the change. I'm looking into this further.

**Comment by kattni** [comment]
Thanks for your patience! We've sorted it.

**Comment by dcbriccetti** [comment]
Hurray!

**Comment by ladyada** [comment]
yayy!

**Comment by siddacious** [comment]
🎉 🎉 HUZZAH! 🎉 🎉

**Pull request merged**
